site_name: fairsense

google_analytics:
  - UA-132343476-2
  - auto

# Set navigation here
nav:
  - Home: index.md
  - API Reference:
    - data_management module:
        - factory module: api/data_management_factory.md
        - processing module: api/data_management_processing.md
    - indices module: api/indices.md
    - visualization module: api/visualization.md
    - utils module:
        - fairness_objective module: api/utils_fairness_objective.md
        - dataclasses module: api/utils_dataclasses.md
  - Tutorials:
    - "Demo 1: Regression problem": notebooks/demo-regression.ipynb
    - "Demo 2: Classification problem": notebooks/demo-classification.ipynb
  - Contributing: CONTRIBUTING.md

theme:
  name: "material"
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    - scheme: default
      primary: dark
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - mkdocstrings
  - mknotebooks

markdown_extensions:
  - footnotes
  - extra
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences
  - codehilite
  - toc:
      baselevel: 1
      permalink: true
      toc_depth: 1-4
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - css/custom.css

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - js/custom.js

repo_name: "deel-ai/fairsense"
repo_url: "https://github.com/deel-ai/fairsense"
